resources:
- repo: self
  clean: true
trigger:
  batch: true
  branches:
    include:
    - master
schedules:
- cron: "0 17 * * Fri"
  always: true
  displayName: Weekly build
  branches:
    include:
    - master
    
stages:
- stage: build
  jobs:
  - job: build
    pool:
      name: 'Hosted Windows 2019 with VS2019'
    variables:
      BuildConfiguration: 'release'
      BuildPlatform: 'Any CPU'
      Solution: '**\*.sln'
    steps:
    - checkout: self

    - task: NuGetInstaller@0
      displayName: 'NuGet restore **\*.sln'
      inputs:
        solution: '$(Solution)'

    - task: VSBuild@1
      displayName: 'Build solution **\*.sln'
      inputs:
        solution: '$(Solution)'
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: '**\bin\**\jwt.exe'
        TargetFolder: '$(build.artifactstagingdirectory)'
        flattenFolders: true


    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact: jwt'
      inputs:
        targetPath: $(build.artifactstagingdirectory)
        artifactName: jwt
